Add HEXL-FPGA compatibility for DyadicMultiply and KeySwitch
intel/hexl pull request #108
Opened 2022-03-03 00:33 UTC by tgonzalez89-intel

Added an internal implementation for DyadicMultiply and KeySwitch and a CMake option and compiler flag to disable the normal DyadicMultiply and KeySwitch and only leave the internal one available. This makes HEXL compatible with HEXL-FPGA. With this both libraries can use HEXL's header but HEXL-FPGA can override DyadicMultiply and KeySwitch with its own implementation while leaving the internal implementation as a fallback if the user desires to use the CPU implementation.

Renamed all instances of CKKS in all functions and file names.

Added a new root_of_unity_powers_ptr option to KeySwitch. This option will be used in HEXL-FPGA.

2022-03-09 20:06 UTC, hamishun approved these changes

2022-03-09 20:17 UTC, joserochh commented on CMakeLists.txt
> +message(STATUS "HEXL_FPGA_COMPAT:              ${HEXL_FPGA_COMPAT}")
Maybe we can use HEXL_FPGA_COMPATIBLE instead? For explicitness.

2022-03-09 20:32 UTC, joserochh commented on hexl/experimental/seal/key-switch-internal.cpp
> +    assert(root_of_unity_powers_ptr == nullptr);
Is it possible to change this to throw an exception error?

2022-03-10 15:57 UTC, jlhcrawford requested changes

2022-03-10 15:57 UTC, jlhcrawford commented on CMakeLists.txt
> +  add_definitions(-DHEXL_FPGA_COMPAT)
This function has been superseded by `add_compile_definitions`
```suggestion
  add_compile_definitions(HEXL_FPGA_COMPAT)
```

2022-03-10 15:57 UTC, jlhcrawford commented on hexl/include/hexl/experimental/seal/key-switch-internal.hpp
> +               const uint64_t* root_of_unity_powers_ptr = nullptr);
Is there a reason why `root_of_unity_powers_ptr` is not documented in the Doxygen above?

2022-03-10 19:39 UTC, closed without merging

2022-03-10 19:40 UTC, ymeng-git commented
continue as PR 109.