optimize keyswitching
intel/hexl pull request #137
Opened 2022-12-02 17:30 UTC by GelilaSeifu

Avoids precomputation of NTT object for better performance when possible.

2022-12-02 20:07 UTC, joserochh requested changes

2022-12-02 20:07 UTC, joserochh commented on hexl/experimental/seal/key-switch-internal.cpp
> +#include "hexl/experimental/seal/get-ntt.hpp"
Can we change the name of this library to something like ntt-objs.hpp or ntt-cache.hpp?

2022-12-02 20:07 UTC, joserochh commented on hexl/experimental/seal/key-switch-internal.cpp
>  #include "hexl/ntt/ntt.hpp"
Is this still needed after adding new get ntt library?

2022-12-02 20:07 UTC, joserochh commented on hexl/include/hexl/experimental/seal/get-ntt.hpp
> +    lhs ^= rhs + 0x9e3779b9 + (lhs << 6) + (lhs >> 2);
Can we add a comment here saying this is based on Golden Ratio Hashing with seeds?

2022-12-02 22:16 UTC, joserochh approved these changes
LG

2022-12-05 17:30 UTC, jlhcrawford approved these changes

2022-12-05 17:39 UTC, merged