Use MultiplyFactor in more places
intel/hexl pull request #43
Opened 2021-08-11 21:43 UTC by fboemer

Also use pre-conditioned modular multiplication for InvNTT native. No noticeable performance, but it shouldn't hurt.

2021-08-11 22:10 UTC, GelilaSeifu approved these changes
Looks good.

2021-08-12 09:20 UTC, hamishun approved these changes
LG

2021-08-12 09:57 UTC, jlhcrawford requested changes
Minor typo. Also found another typo which I can't comment on because GitHub doesn't allow review of code outside of the commits in a PR for some reason.

On line 376 of `hexl/ntt/ntt-internal.cpp`; `ouput` -> `output`

2021-08-12 09:57 UTC, jlhcrawford commented on hexl/include/hexl/number-theory/number-theory.hpp
> +  /// Barrett factor for multipliations of the form (x * y) mod modulus, where
```suggestion
  /// Barrett factor for multiplications of the form (x * y) mod modulus, where
```

2021-08-12 14:48 UTC, jlhcrawford approved these changes

2021-08-12 14:50 UTC, merged