Faster native NTT
intel/hexl pull request #46
Opened 2021-08-13 19:11 UTC by fboemer

Speeds up native NTT by:
* For MSVC, manually unrolling loops doesn't support `#pragma loop unroll` or similar
* Extracting separate `t=1, 2, 4, 8` loops

With these changes, I'm seeing on a Mac:
Before:
![Screen Shot 2021-08-13 at 12 10 06 PM](https://user-images.githubusercontent.com/7935794/129407506-bff66bf0-9012-4b8e-9dd4-1ed175a08d2a.png)

After:
![Screen Shot 2021-08-13 at 12 08 40 PM](https://user-images.githubusercontent.com/7935794/129407381-1cf22936-5ac4-4455-b23e-57b36b2bbdde.png)

Also standardize `W_op` to `W` and `(W_precon | W_op_precon)` to `W_precon` and fix a few documentation bugs

2021-08-13 19:17 UTC, fboemer commented on hexl/ntt/fwd-ntt-avx512.cpp
> -/// @brief AVX512 implementation of the forward NTT
Documentation already present in header, no need to duplicate here.

2021-08-13 19:17 UTC, fboemer commented on hexl/ntt/inv-ntt-avx512.cpp
> -/// @brief AVX512 implementation of the inverse NTT
Documentation already in header, no need t  duplicate here

2021-08-13 19:18 UTC, fboemer commented on hexl/ntt/inv-ntt-avx512.hpp
> +/// @param[in] inv_root_of_unity_powers Powers of inverse 2n'th root of unity in
Doxygen would usually catch this, except we only require docstrings for public header files, i.e. those in `hexl/include`.

2021-08-13 21:26 UTC, GelilaSeifu approved these changes
LGTM

2021-08-16 11:33 UTC, jlhcrawford requested changes
Some typos and comments. 

What is the convention we are choosing regarding the copyright of new files? I notice that `ntt-default.{h,c}pp` are new files yet have a copyright from 2020-2021. Are we creating copyrights for the years at which the files exist (i.e. 2021 only for the files in question) or keeping them the same across all files regardless of the lifetime of the file itself?

There are a couple other typos I've noticed just outside the "comment-able" areas. I'll fix them myself to avoid the hassle.

2021-08-16 11:33 UTC, jlhcrawford commented on hexl/ntt/fwd-ntt-avx512.hpp
>  /// @param[in] n Size of the transfrom, i.e. the polynomial degree. Must be a
```suggestion
/// @param[in] n Size of the transform, i.e. the polynomial degree. Must be a
```

2021-08-16 11:33 UTC, jlhcrawford commented on hexl/ntt/inv-ntt-avx512.hpp
>  /// @param[in] n Size of the transfrom, i.e. the polynomial degree. Must be a
```suggestion
/// @param[in] n Size of the transform, i.e. the polynomial degree. Must be a
```

2021-08-17 14:08 UTC, jlhcrawford approved these changes
LGTM

2021-08-17 14:14 UTC, merged